path: C:/Users/esalt/OneDrive/Desktop/new2/cam/robo  # dataset root dir
train: train/images  # train images (relative to 'path')
val: train/images  # val images (relative to 'path')

# Classes
nc: 1  # number of classes (make sure this matches the actual number of classes)
names:
  0: Nut
